### ISSUE TITLE
Console commands

### ISSUE THREAD

**Issue by ezanchi** [fj317/PumpBot#17]
It would be really useful if we could run the program through CMD and enter all the settings and coin with parameters

**Comment by ArielKatzir** [comment]
Would you please consider expanding on this request? We are currently happy with the config file and think that manually inputting and choosing the settings every time the program runs is unneeded. Furthermore, some people who might not be too comfortable with crypto, might prefer our default values as they might not be confident with settings they might not fully understand. And of course, we want to minimise loss for our users and be as fair as we can.

**Comment by ezanchi** [comment]
> Would you please consider expanding on this request? We are currently happy with the config file and think that manually inputting and choosing the settings every time the program runs is unneeded. Furthermore, some people who might not be too comfortable with crypto, might prefer our default values as they might not be confident with settings they might not fully understand. And of course, we want to minimise loss for our users and be as fair as we can.

You can keep the config file and UI and also allow for more advanced users to change some/all parameters via CMD and set the parameters with commands. Everything not changed with a command would be defaulted to the config file (API key and else)
So this: 
./pumpbot.py
would take all parameters from config file and this:
./pumpbot.py -tp 130
would take everything from config file except Take Profit which it would override with the set 130

**Comment by fj317** [comment]
It would be possible to implement this but it seems to be a lot of effort for a feature that most people won't be using.
It also wouldn't speed up buy/sell orders, in fact it would probably slow them. This is because if you entered the coin as an argument, the program would need to load libraries etc before buying the coin, whereas in the current version these libraries are already loaded before you enter the coin.
I'll add it to the future feature list but it won't be a priority feature. If you want to implement it yourself feel free to contribute.
