### ISSUE TITLE
Text Scrapper

### ISSUE THREAD

**Issue by subevilx** [fj317/PumpBot#50]
U can add a scrape feature through discord,py regex which will look for the name of the name as soon as it is released on

**Comment by fj317** [comment]
This isn't viable because most Discord servers release the coin in an image format to prevent this exact thing. 
Anyhow, if implemented the best case scenario is reducing the time by around 1 second, worst case scenario the program gets stuck trying to decipher which coin it is. 
I don't think it's worth the effort to implement this feature so closing the issue.
