### ISSUE TITLE
A question about buying option

### ISSUE THREAD

**Issue by bouheddadj** [fj317/PumpBot#51]
Hello, I hope you're doing so well, I have a question, If i put buyLimit at 1.00, It's going to market buy ? If it's not how to market buy with this lovely bot ? Thanks for further help.

**Comment by fj317** [comment]
It will still send a limit buy order to Binance, however it will be at the average market price of the coin rather than the current market price of it. This is done to avoid the bot buying pre-dumped coins and avoid you buying coins at a price that will not be profitable for you to sell at.
It is not possible to just send a market buy using the bot as is. You will have to change the source code of the bot to complete a market buy. You would change lines 173-176 to the following I belive:
```
order = client.order_market_buy(
        symbol=tradingPair,
        quantity=amountOfCoin)
```
Hope this answers your question :)

**Comment by bouheddadj** [comment]
You did answer my question, Thank you so much, Just one more little question, if i do these change and i set profit at 10% for example, he will take the market buy price and add the 10% profit? or i need more changes to set this up ? thanks again

**Comment by fj317** [comment]
If you set a 10% profit margin (be aware to get 10% you would enter 110 in config.json) this will sell the coin at 10% MORE than the price you paid for the coins.
Eg if you bought some coins with 10 BC and set your profit margin to 110 in config.json, you would create a sell order that would produce 11 BTC if fulfilled.
