### ISSUE TITLE
Placing order: Market price minus x percentage.

### ISSUE THREAD

**Issue by captjones** [fj317/PumpBot#62]
**Is your feature request related to a problem? Please describe.**
No problem. Cool beans!

**Describe the solution you'd like**
I noticed it's possible to buy **at market** (from the deleted issue thread). Wondering if it's difficult to implement market order **minus** x percentage.
Say, the market price for a coin is x. It would be unwise to buy yourself into a scam at the market price. A safer solution would be to buy in at x-n%.

Greetings from Estonia.

**Comment by fj317** [comment]
This is possible and I believe already implemented. 
Basically the 'buyLimit' parameter in config.json states how much above market price you are willing to pay. Since the default is 1.15 I don't see why it wouldn't possible to change this to a value like 0.8 which will mean you will create a order for the coin at 0.8 * market price (i.e. 80% of market price). 
The buylimit parameter is used to prevent yourself buying into a scam like you mentioned as it limits the price that you will pay for the coin.

**Comment by captjones** [comment]
I think it buys at x*24 hour average, not x*market, since with 0.99 multiplier it bought the coin for far above market price (overpaid. I don't even understand how it's possible, Binance should pick the closest sell price).
