### ISSUE TITLE
Error code -2010

### ISSUE THREAD

**Issue by schuesslerf** [fj317/PumpBot#77]
Hey mate,

refering to the same issue of #73, I'm getting the same error now...

Tried with my old version 1.4, as well as with 1.6, ending up with error code -2010 (from binance), saying "Account has insufficient balance for requested action". 

What's interesting is that this doesn't always happen.. Sometimes its working, sometimes it's not.. For me, it feels like the bot tries to place the sell order, before the buy order got executed, so it has insufficient balance to create the sell order.. Really weird somehow...

You have any idea or are familiar with this issue? Trying to fix as well... What's weird is that code didn't change on my side since the last pump i participated and there, everything worked like a charm.... Maybe a problem with the Binance API?

**Comment by schuesslerf** [comment]
Okay, so it seems like I found a more or less working fix for me to try in a pump today...
I just set the amount to sell to `coinOrderQty*0.98`, which seems to do the trick for now... 

I noticed, that the bot seems to somehow and sometimes use the same value of amount to sell, so my wallet showed something like 57.8 of the coin and the bot tried to place a sell order of 58.2, so of course, it didn't work, that's why that seems to be a temp fix for me to try today...

However, I noticed that there actually seems to be some ind of issue with that quantity in general, as in one test, I bought 38 QTUM, I could also see that number in my order history - however prinitng the `coinOrderInfo` variable gave me a `qty` of 29.... it's really weird and I don't know why this happens, maybe they hat some change on the api or sth?

**Comment by kuratkull** [comment]
"quotedCoin": "BTC",
    "buyLimit": 1,
    "percentOfWallet":100,
    "manualQuoted": 0.00000000,
    "profitMargin": 150,
    "stopLoss": 0.90,
    "endpoint": "api1",

With these values, I have an error corrected. BUT when I gave a buy order for any coin, the price of the coin is 1379 satoshi and the order value for buying is 1342 satoshi. does not get instant. Do you have the same problem?

**Comment by kuratkull** [comment]
Why is it giving a lower purchase order than the instant coin price? Do you have the same problem?

**Comment by fj317** [comment]
> 
> 
> Why is it giving a lower purchase order than the instant coin price? Do you have the same problem?

This is happening because your buyLimit is 1. See the [readme](https://github.com/fj317/PumpBot#configjson)'s descirption of the buyLimit parameter.

**Comment by fj317** [comment]
> 
> 
> Okay, so it seems like I found a more or less working fix for me to try in a pump today...
> I just set the amount to sell to `coinOrderQty*0.98`, which seems to do the trick for now...
> 
> I noticed, that the bot seems to somehow and sometimes use the same value of amount to sell, so my wallet showed something like 57.8 of the coin and the bot tried to place a sell order of 58.2, so of course, it didn't work, that's why that seems to be a temp fix for me to try today...
> 
> However, I noticed that there actually seems to be some ind of issue with that quantity in general, as in one test, I bought 38 QTUM, I could also see that number in my order history - however prinitng the `coinOrderInfo` variable gave me a `qty` of 29.... it's really weird and I don't know why this happens, maybe they hat some change on the api or sth?

This is weird I've encountered it a few times too. If I have some free time I'll try and do some rigorous testing into what is causing this error so I can fix it.

**Comment by kuratkull** [comment]
@fj317 Can we give a manual sale?

**Comment by fj317** [comment]
The bot should attempt to manually sell at market price if an error occurs already.

**Comment by kuratkull** [comment]
@fj317 I have solved this end as follows; the balance is first 50% and then it continues to operate 100%. does not repeat the error then.

**Comment by fj317** [comment]
So you set the percentOfWallet to 50?

**Comment by kuratkull** [comment]
YES is trading with 50% first. I can then use it 100%. the error then goes away.

**Comment by percyparedes** [comment]
So what should i do to solve the problem ? Set my "percentOfWallet" to 50? Or can i set it to 100?

**Comment by schuesslerf** [comment]
Yeah, another missed chance on a nice pump....

Again, I got the error when trying to buy, saying "A BinanceAPI error has occurred. Code = -2010".., further down saying: "Account has insufficient balance for requested action"...

Getting kinda annoying right now :(

**Comment by Jason-Soo** [comment]
@fj317 Hi just some tips from a bot seller,
Firstly, python would auto round up when it send the amount to binance which means if amount of coin purchased are 0.1789 it will set sell order 0.179 which would cause insufficient balance

Secondly, if the user has no bnb for fees it would take the coin X purchased and minus some for fees e.g. purchased amount 0.1789 and after fees might be 0.177 and again it will trigger another insufficient balance

Thirdly, most common problem some coins/tokens are traded in whole number which means no decimal e.g. if I purchased 2 coin X and I don't have any bnb for fees it would deduct again from that coin and becomes 1.997 and if you try to set sell order it will throw lot size error and if you manually sell it, binance would convert it to 1 and that 0.997 you will have to go to your wallet settings and convert

Probably the best temporary fix for this error with no lot size problem would be if user has no bnb for fees then take (amount of coin purchase - lot size), because * 0.98 doesn't work for all coins some would throw lot size error, doing this at most just leaving like $0.3 behind but best would be to have some bnb for fees

**Comment by schuesslerf** [comment]
Okay, let's just get some BNB then, shouldn't be a problem :)

**Comment by Jason-Soo** [comment]
Problem 1 might occur if it is left on default it will auto round up, if format it based on precision then that would not occur. Something like `newValue1 = "{:0.0{}f}".format(newValue1, precision)`

**Comment by fj317** [comment]
> Firstly, python would auto round up when it send the amount to binance which means if amount of coin purchased are 0.1789 it will set sell order 0.179 which would cause insufficient balance

The rounding shouldn't be an issue since I created my own rounding function that rounds the coin to the correct number of decimal places depending upon how many decimal places Binance uses.

> Secondly, if the user has no bnb for fees it would take the coin X purchased and minus some for fees e.g. purchased amount 0.1789 and after fees might be 0.177 and again it will trigger another insufficient balance

This is written into the readme already with good instructions.

> Thirdly, most common problem some coins/tokens are traded in whole number which means no decimal e.g. if I purchased 2 coin X and I don't have any bnb for fees it would deduct again from that coin and becomes 1.997 and if you try to set sell order it will throw lot size error and if you manually sell it, binance would convert it to 1 and that 0.997 you will have to go to your wallet settings and convert

If users had BNB, like recommended, this wouldn't be an issue. Also I'll have to spend a lot of time implementing the logic when the alternative is getting some BNB which is very easy and quick.

**Comment by rayures** [comment]
i also have this issue with BNB available.

when doing a testrun it gives: 
```
Investing amount for BTC: 0.001
Investing amount in USD: 59.12

Coin pair: sc
Buy order has been made!
Processing sell order.
A BinanceAPI error has occurred. Code = -2010
```

```
config: 
    "quotedCoin": "BTC",
    "buyLimit": 1.15,
    "percentOfWallet": 10,
    "manualQuoted": 0.00100000,
    "profitMargin": 101,
    "stopLoss": 0.90,
    "endpoint": "default",
```

**Comment by fj317** [comment]
It's because your profit margin is so low I think. The program needs the profit margin to be higher than the current price of the coin otherwise it'll fail. Since your profit margin is 101 the program tries to sell the coin at the same price it bought it at basically and this results in an error since OCO orders have strict rules.

**Comment by rayures** [comment]
Ah, lol. Thought 101 meant something else ;-) will test that later. Tnx for the pointer.
