### ISSUE TITLE
Limit order or market order

### ISSUE THREAD

**Issue by Sofficino97** [fj317/PumpBot#8]
hello, sorry if I open a request here, I wanted to ask since the bot makes an order in limit and not in market, isn't it that during the pump it fails to buy?
did you test it during a pump?
The settings I would like to use:
buy 0%
profit 140% (40% profit)
wallet 80%
stoploss 0.9
Thank you so much

**Comment by fj317** [comment]
The idea in using a limit buy is to ensure you don't buy pre-pumped coins. If you market buy you will always buy no matter what the price of the coin. This means if the coin has been pre-pumped and the price of the coin has skyrocketed you will still buy it. With the limit buy it tries to reduce this by only allowing an order at the price when you inputted the coin pair. 
Its not ideal and I will probably at some point improve the buying but for now it works fine.
If you want to change from a LIMIT to a MARKET buy you can manually change the code yourself:

- On line 84 change this to 'order = client.order_market_buy(' 
- Remove line 87 (price = averagePrice). 
- This will now execute a market order rather than a limit.
